### ISSUE TITLE
 Unhandled Exception: DioException [bad response]: The request returned an invalid status code of 400

### ISSUE THREAD

**Issue by CanArslanDev** [faithoflifedev/google_vision_workspace#14]
Hello, when I tried it yesterday, the api was working, but when I tried it today, I saw that it was not working. I checked the service_credentials.json file, renewed it and created a new API key, but it didn't work.

This Code 
```
final googleVision = await GoogleVision.withJwt(jwtFromAsset);
```
Error:

```E/flutter ( 8608): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [bad response]: The request returned an invalid status code of 400.
E/flutter ( 8608): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507:7)
E/flutter ( 8608): #1      _RootZone.runUnary (dart:async/zone.dart:1661:54)
E/flutter ( 8608): #2      _FutureListener.handleError (dart:async/future_impl.dart:174:22)
E/flutter ( 8608): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter ( 8608): #4      Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter ( 8608): #5      Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter ( 8608): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60:12)
E/flutter ( 8608): #7      _Completer.completeError (dart:async/future_impl.dart:26:5)
E/flutter ( 8608): #8      Future.any.onError (dart:async/future.dart:620:45)
E/flutter ( 8608): #9      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter ( 8608): #10     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
E/flutter ( 8608): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
```
Edit: I found that the problem was caused by the token generator in the package. But I still haven't figured it out.
![image](https://github.com/faithoflifedev/google_vision/assets/76579053/22090f67-7503-4794-9bcf-7df9f283f412)

**Comment by faithoflifedev** [comment]
Hi @CanArslanDev , I've published a new version of the package.  It probably won't solve the error you show above.  The source now includes an example `face_detection.dart` which can be used to test your Google provided jwt token from the command line.  

I'm seeing that the code is working as expected when I run the example.
